---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "ğŸ·ï¸npm-deps"
      - "â˜ï¸ci"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "ğŸ·ï¸npm-deps"
      - "ğŸ“¦packages"
      - "â˜ï¸ci"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "ğŸ·ï¸npm-deps"
      - "ğŸ“¦packages"
      - "â˜ï¸ci"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      time: "00:10"
      timezone: "Asia/Calcutta"
    versioning-strategy: widen
    target-branch: "main"
    labels:
      - "ğŸ·ï¸npm-deps"
      - "ğŸ“¦packages"
      - "â˜ï¸ci"
