version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    target-branch: "main"
    time: "00:10"
    timezone: "Asia/Calcutta"
    labels:
      - "npm-deps"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    target-branch: "main"
    time: "00:20"
    timezone: "Asia/Calcutta"
    labels:
      - "ğŸ·ï¸ npm"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    target-branch: "main"
    time: "00:20"
    timezone: "Asia/Calcutta"
    labels:
      - "ğŸ·ï¸ npm"
