---
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:

  pr:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          pass_on_octokit_error: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: .
          scan-type: fs
          scan-ref: .
          output: dependency-results.sbom.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  triage:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/labeler@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: ğŸ‘· Build
        run: |
          pnpm run -r ci:env-copy
          pnpm run build
          pnpm run -r ci:env-delete
          pnpm run -r build:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: ğŸ‘• Lint
        run: pnpm run lint

  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: Playwright Deps
        run: npx playwright install --with-deps

      - name: ğŸ‘· Build
        run: |
          pnpm -C apps/admin build
          pnpm -C apps/web build

      - name: ğŸŒ E2E Test
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            artifacts/@templ/admin/e2e-report/index.html
            artifacts/@templ/web/e2e-report/index.html
          retention-days: 30

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node_version }}

      - name: ğŸ§ª Unit Test
        run: pnpm run test

      - name: ğŸ“š Storybook build
        run: pnpm run -C packages/ui build

      - name: ğŸš¨ Storybook Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          npx playwright install --with-deps
          pnpm -C packages/ui test:storybook:ci

  action-timeline:
    needs: [build, e2e_test, lint, pr, test, trivy_scan, triage]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v1
