---
name: Issue Helper

on:
  issues:
    types: [opened, labeled]

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ğŸ”’lock'
    steps:
      - name: Lock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: lock-issue
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}

  unlock-issues:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ğŸ”“unlock'
    steps:
    - name: Unlock issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'unlock-issue'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}

  close-issues:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'âŒclose'
    steps:
      - name: need reproduction
        uses: actions-cool/issues-helper@v3
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: need reproduction
          inactive-day: 7

  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'welcome'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: Hi @${{ github.event.issue.user.login }}, welcome!
          issue-emoji: '+1, -1, eyes'
